Header + Footer + Collection_details
turcottep/cryptus pull request #30
Opened 2022-02-07 15:41 UTC by Tristan-01

2022-02-10 18:58 UTC, GuilaumeBrassard approved these changes
It's good now!

2022-02-14 14:51 UTC, turcottep commented
![image](https://user-images.githubusercontent.com/32850285/153886850-edfacb04-7eae-4616-9316-88aa040d4d56.png)

2022-02-14 17:13 UTC, alexandrelafleur requested changes, later dismissed

2022-02-14 17:13 UTC, alexandrelafleur commented on cryptus-app/components/template/pagetemplate/pagetemplate.tsx
> +import Header from "../../header/old_header";
maybe this is the problem with the old header?

2022-02-14 17:13 UTC, alexandrelafleur commented on cryptus-app/components/wallet_viewer/collection_details/collection_infos/collection_infos.tsx
> +);
Integrate `<div className={s.name}>` into this function instead of the parent code

2022-02-14 17:13 UTC, alexandrelafleur commented on cryptus-app/components/wallet_viewer/collection_details/collection_infos/collection_infos.tsx
> +const OwnedNftsFromCollectionNumber = (props: { number: number }) => (
same, integrate, <div className={s.number}>

2022-02-14 17:13 UTC, alexandrelafleur commented on cryptus-app/components/wallet_viewer/collection_details/collection_infos/collection_infos.tsx
> +const OwnedNftsFromCollectionNumber = (props: { number: number }) => (
`<div className={s.number}>`

2022-02-14 17:13 UTC, alexandrelafleur commented on cryptus-app/components/wallet_viewer/collection_details/collection_viewer/collection_viewer.tsx
> +  ];
get collection from props instead, and code this test collection at the place where the backend call would be made

2022-02-14 17:13 UTC, alexandrelafleur commented on cryptus-app/components/wallet_viewer/collection_details/collection_viewer/nft_block/nft_block.tsx
> +        <NftPictureBlockInCollection url= "login" nft= {props.nft}/>
does this actually work with spaces between url= and "login"

2022-02-14 17:13 UTC, alexandrelafleur commented on cryptus-app/components/wallet_viewer/collection_details/collection_viewer/nft_block/nft_block.tsx
> +      <div className={s.none}>
put this div inside the NftPictureBlockInCollection function instead, so the main code is cleaner

2022-02-14 17:13 UTC, alexandrelafleur commented on cryptus-app/components/wallet_viewer/collection_details/collection_viewer/nft_block/nft_block.tsx
> +      <div className={s.none}>
same

2022-02-17 17:02 UTC, merged