Market viewer
turcottep/cryptus pull request #39
Opened 2022-02-14 13:53 UTC by Tristan-01

2022-02-14 14:25 UTC, GuilaumeBrassard commented on cryptus-app/pages/market.module.scss
> +  width: 100%;
Séparer en groupe ici pour que ça soit plus clean

2022-02-14 14:25 UTC, GuilaumeBrassard commented on cryptus-app/pages/market.module.scss
> +  width: 100%;
Fait le partout dans ce fichier

2022-02-14 14:25 UTC, GuilaumeBrassard commented on cryptus-app/components/market_viewer/collection_row/price_info/price_info.tsx
> +function FloorPriceDelta(props: { price: number, delta: number, currency: string }) {
Tu peux export la fonction pour qu'on l'utilise ailleurs

2022-02-14 14:25 UTC, GuilaumeBrassard commented on cryptus-app/components/market_viewer/collection_row/price_info/price_info.tsx
> +// Need to add more display options (different currencies, # of digits after comma, etc.)
Tu peux export la fonction

2022-02-14 14:25 UTC, GuilaumeBrassard commented on cryptus-app/components/market_viewer/collection_row/price_info/price_info.tsx
> +// Need to add more display options (different currencies, # of digits after comma, etc.)
Ou tu peux la mettre dans lib

2022-02-14 17:37 UTC, alexandrelafleur requested changes

2022-02-14 17:37 UTC, alexandrelafleur commented on cryptus-app/components/market_viewer/collection_row/collection_info/collection_info.module.scss
> +  height: 66%;
use px

2022-02-14 17:37 UTC, alexandrelafleur commented on cryptus-app/components/market_viewer/collection_row/collection_info/collection_info.module.scss
> +    height: 34%;
use px (almost all the time px, except for 50% or 100%

2022-02-14 17:37 UTC, alexandrelafleur commented on cryptus-app/components/market_viewer/collection_row/collection_info/collection_info.module.scss
> +    max-width: 40%;
us px, and width instead of max-width

2022-02-14 17:37 UTC, alexandrelafleur commented on cryptus-app/components/market_viewer/collection_row/collection_info/collection_info.module.scss
> +    height: 100%;
use px

2022-02-14 17:37 UTC, alexandrelafleur commented on cryptus-app/components/market_viewer/collection_row/collection_info/collection_info.module.scss
> +    font-weight: 400;
use px, and $v. (global variable)

2022-02-14 17:37 UTC, alexandrelafleur commented on cryptus-app/components/market_viewer/collection_row/collection_info/collection_info.module.scss
> +    height: 100%;
use px

2022-02-14 17:37 UTC, alexandrelafleur commented on cryptus-app/components/market_viewer/collection_row/collection_info/collection_info.module.scss
> +    font-size: 75%;
use px and global variable

2022-02-14 17:37 UTC, alexandrelafleur commented on cryptus-app/components/market_viewer/collection_row/collection_row.module.scss
> +  width: 35%;
use px

2022-02-14 17:37 UTC, alexandrelafleur commented on cryptus-app/components/market_viewer/collection_row/collection_row.module.scss
> +    width: 50%;
use px (50% would only really work if we wanted to do a 50-50, but then again, px is preferred

2022-02-14 17:37 UTC, alexandrelafleur commented on cryptus-app/components/market_viewer/collection_row/collection_row.module.scss
> +    width: 25%;
use px

2022-02-14 17:37 UTC, alexandrelafleur commented on cryptus-app/components/market_viewer/collection_row/collection_row.tsx
> +    </div>
do you really need s.infos, s.graph and s.price ? Or could it a) be removed, or b) be integrated in their children components

2022-02-14 17:37 UTC, alexandrelafleur commented on cryptus-app/components/market_viewer/collection_row/price_info/price_info.module.scss
> +  height: 66%;
use px

2022-02-14 17:37 UTC, alexandrelafleur commented on cryptus-app/components/market_viewer/collection_row/price_info/price_info.module.scss
> +    height: 33%;
use px

2022-02-14 17:37 UTC, alexandrelafleur commented on cryptus-app/components/market_viewer/collection_row/price_info/price_info.module.scss
> +    font-weight: 700;
use px and global

2022-02-14 17:37 UTC, alexandrelafleur commented on cryptus-app/components/market_viewer/collection_row/price_info/price_info.module.scss
> +    font-weight: 700;
use px and global

2022-02-14 17:37 UTC, alexandrelafleur commented on cryptus-app/components/market_viewer/collection_row/price_info/price_info.module.scss
> +    color: rgb(53,199,90);
use global

2022-02-14 17:37 UTC, alexandrelafleur commented on cryptus-app/components/market_viewer/collection_row/price_info/price_info.module.scss
> +    font-weight: 700;
use global and px

2022-02-14 17:37 UTC, alexandrelafleur commented on cryptus-app/components/market_viewer/collection_row/price_info/price_info.tsx
> +      </div>
integrate s.fp and s.fpd into their children component

2022-02-14 17:37 UTC, alexandrelafleur commented on cryptus-app/components/market_viewer/collection_row/price_info/price_info.tsx
> +  const curr = props.currency
use props destructuring instead -> `const {price, delta, curr} = props;`

2022-02-14 17:37 UTC, alexandrelafleur commented on cryptus-app/components/market_viewer/collection_row/price_info/price_info.tsx
> +    const curr = props.currency
use props destructuring

2022-02-14 17:37 UTC, alexandrelafleur commented on cryptus-app/components/market_viewer/collection_row/price_info/price_info.tsx
> +  const collection = props.collection
use props destructuring

2022-02-14 17:37 UTC, alexandrelafleur commented on cryptus-app/components/market_viewer/favorite_collections/favorite_collections.module.scss
> +  height: 6.25%;
use px

2022-02-14 17:37 UTC, alexandrelafleur commented on cryptus-app/components/market_viewer/favorite_collections/favorite_collections.module.scss
> +  position: sticky;
why does the position need to be sticky? It's a real question I don't know why? Thanks!

2022-02-14 17:37 UTC, alexandrelafleur commented on cryptus-app/components/market_viewer/favorite_collections/favorite_collections.module.scss
> +    width: 10%;
use px

2022-02-14 17:37 UTC, alexandrelafleur commented on cryptus-app/components/market_viewer/favorite_collections/favorite_collections.module.scss
> +    width: 90%;
use px

2022-02-14 17:37 UTC, alexandrelafleur commented on cryptus-app/components/market_viewer/favorite_collections/favorite_collections.module.scss
> +    font-weight: 600
use global

2022-02-14 17:37 UTC, alexandrelafleur commented on cryptus-app/components/market_viewer/favorite_collections/favorite_collections.tsx
> +      <div className={s.title}>
integreate into children

2022-02-14 17:37 UTC, alexandrelafleur commented on cryptus-app/components/market_viewer/market_collections/market_collections.module.scss
> +  height: 6.25%;
use px

2022-02-14 17:37 UTC, alexandrelafleur commented on cryptus-app/components/market_viewer/market_collections/market_collections.module.scss
> +    height: auto;
not needed I believe

2022-02-14 17:37 UTC, alexandrelafleur commented on cryptus-app/components/market_viewer/market_collections/market_collections.module.scss
> +    width: 90%;
use px

2022-02-14 17:37 UTC, alexandrelafleur commented on cryptus-app/components/market_viewer/market_collections/market_collections.module.scss
> +    font-weight: 600
use global

2022-02-14 17:37 UTC, alexandrelafleur commented on cryptus-app/components/market_viewer/market_collections/market_collections.tsx
> +      <div className={s.title}>
integrate in children

2022-02-14 17:37 UTC, alexandrelafleur commented on cryptus-app/components/market_viewer/market_collections/market_collections.tsx
> +      <div className={s.market}>
create arrow function instead

2022-02-14 17:37 UTC, alexandrelafleur commented on cryptus-app/components/market_viewer/favorite_collections/favorite_collections.tsx
> +      <div className={s.favorites}>
create arrow function instead

2022-02-14 17:37 UTC, alexandrelafleur commented on cryptus-app/components/market_viewer/market_viewer.module.scss
> +  position: sticky;
why sticky?

2022-02-14 17:37 UTC, alexandrelafleur commented on cryptus-app/pages/market.tsx
> +        <div className={s.viewer}>
do you really need this div? Or could it be removed?

2022-02-14 17:37 UTC, alexandrelafleur commented on cryptus-app/styles/_variables.scss
> +$overview-height: 100%
don't use % in global variables. If it really is 100% write it in the css instead, if it should be in px, write in px in global

2022-02-17 15:43 UTC, alexandrelafleur approved these changes

2022-02-17 15:45 UTC, alexandrelafleur commented
ton package-lock est fucked @Tristan-01 , can you fix that? Jsuis pas exactement sur comment, if you don't know, ask google and then @turcottep

2022-02-17 16:44 UTC, merged