settings page for v1
turcottep/cryptus pull request #52
Opened 2022-03-12 20:30 UTC by GuilaumeBrassard

2022-03-13 20:59 UTC, turcottep requested changes

2022-03-13 20:59 UTC, turcottep commented on cryptus-app/components/header/contextual_menu_button/contextual_menu_button.tsx
>      if (img == "/icons/menu_icon.png") {
remplace les ... par un icone de gear

2022-03-13 20:59 UTC, turcottep commented on cryptus-app/components/market_overview/search_bar/search_bar.tsx
> +      <input type="text" className={s.searchTerm} placeholder="Search coming soon!" />
![image](https://user-images.githubusercontent.com/32850285/158076432-17319411-20ca-4a23-80a4-0b764a62a6ac.png)
enlève le contour et l'icone est trop gros

2022-03-13 20:59 UTC, turcottep commented on cryptus-app/components/settings/settings.module.scss
> +.settingRows {
![image](https://user-images.githubusercontent.com/32850285/158076473-7505f4dc-555b-4a17-9cb8-9703e433e5b8.png)
le texte est trop gros, trop collé.
Les icones ne sont pas tous de la même grandeur et ne sont pas centrés sur la colonne

2022-03-13 21:00 UTC, turcottep commented on cryptus-app/components/settings/settings.module.scss
> +.settingRows {
Il faudrait aussi que tu puisses cliquer sur la ligne au complet, pas seulement sur l'icone

2022-03-17 18:16 UTC, GuilaumeBrassard commented on cryptus-app/components/market_overview/search_bar/search_bar.tsx
> +      <input type="text" className={s.searchTerm} placeholder="Search coming soon!" />
Je réussi pas à le reproduire, mais j'ai diminué l'icon

2022-03-28 00:30 UTC, turcottep approved these changes

2022-03-28 00:48 UTC, merged